version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
  node: circleci/node@5.0.3
  heroku: circleci/heroku@1.2.6
  go: circleci/go@1.7.1
jobs:
  build-and-test-gin-app:
    executor:
      name: go/default
      tag: '1.18'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: 
          name: Check fmt
          command: gofmt -l .
      - run:
          name: Generate binaries
          command: make go-build
      - run:
          name: Run unit tests
          command: make go-test
  build-react-app:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Generate production build
          command: make react-build
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: sudo apt-get update -y
      - run:
          command: sudo apt-get install -y xvfb
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - store_artifacts:
          path: ./cypress/screenshots/
      - store_artifacts:
          path: ./cypress/videos/
  build-and-upload-react-app:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Generate production build
          command: make react-build
      - run: 
          name: Upload to IBM COS bucket
          command: npm run deploy:client
workflows:
    main:
      jobs:
        - build-react-app
        - build-gin-app
    daily:
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - test
    build-deploy-test:
      jobs:
        - build-and-upload-react-app:
            filters:
              branches:
                only:
                  - master
        - build-gin-app:
            filters:
              branches:
                only:
                  - master
        - heroku/deploy-via-git:
            requires:
              - build-and-upload-react-app
              - build-gin-app
            filters:
              branches:
                only:
                  - master
            force: true
        - test:
            requires:
              - heroku/deploy-via-git
            filters:
              branches:
                only:
                  - master