version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.3
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Generate production build
          command: make react-build
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: sudo apt-get update -y
      - run:
          command: sudo apt-get install -y xvfb
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - store_artifacts:
          path: ./cypress/screenshots/
      - store_artifacts:
          path: ./cypress/videos/
workflows:
    main:
      jobs:
        - build
    hourly:
      triggers:
        - schedule:
            cron: "0 * * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - test
    deploy:
      jobs:
        - heroku/deploy-via-git:
            pre-steps:
              - run:
                  name: Generate production bundle
                  command: make react-build
              - run: 
                  name: Upload to IBM COS bucket
                  command: node upload-cos.js 
            filters:
              branches:
                only:
                  - master