version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Run tests
          command: make react-build
workflows:
    main:
      jobs:
        - build
    hourly:
      triggers:
        - schedule:
            cron: "0 * * * *"
            filters:
              branches:
                only:
                  - main
      jobs:
        - build