version: 2.1
orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.3
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Generate production build
          command: make react-build
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - store_artifacts:
          path: ./cypress/screenshots/
      - store_artifacts:
          path: ./cypress/videos/
workflows:
    main:
      jobs:
        - build
    hourly:
      triggers:
        - schedule:
            cron: "0 * * * *"
            filters:
              branches:
                only:
                  - main
      jobs:
        - test
    deploy:
      filters:
        branches:
          only:
            - main
      jobs:
        - heroku/deploy-via-git